# Question 4

In [ ]:
import numpy as np 
A_Test = np.matrix([[1,2],[2,3]])
eval, evec = (np.linalg.eig(A_Test))
print(evec[0])
print(evec[1])

print(np.dot(evec[0],np.transpose(evec[1])))

# Question 1

In [22]:
import numpy as np
import pandas as pd
from sympy import *

A_Test_1 = np.matrix([[-0.5,-1],[1,1]])
A_Test_1_inv = np.linalg.inv(A_Test_1)

A_Test_2 = np.matrix([[0,1],[-2,-3]])

print(np.dot(A_Test_1,np.dot(A_Test_2,A_Test_1_inv)))

print("Matrix : {} ".format(Matrix(A_Test_2)))
P, D = Matrix(A_Test_2).diagonalize()        
print("Diagonal of a matrix : {}".format(D))  
eval, evec = (np.linalg.eig(A_Test_2))
print(eval[0], eval[1])
print(evec[0])
print(evec[1])


[[-1.   1.5]
 [ 0.  -2. ]]
Matrix : Matrix([[0, 1], [-2, -3]]) 
Diagonal of a matrix : Matrix([[-2, 0], [0, -1]])
-1.0 -2.0
[[ 0.70710678 -0.4472136 ]]
[[-0.70710678  0.89442719]]


# Question 6

In [12]:
import numpy as np 
A_Test = np.matrix([[3,2,4],[2,0,2],[4,2,3]])
eval, evec = (np.linalg.eig(A_Test))
print(evec[0])
print(evec[1])

[[-0.74535599  0.66666667 -0.19487224]]
[[ 0.2981424   0.33333333 -0.78536781]]


# Question 7

In [21]:
import numpy as np
import pandas as pd
from sympy import *

A_Test_complex = np.matrix([[1, 1j],[-1j,1]], dtype=complex)

print("Matrix : {} ".format(Matrix(A_Test_complex)))
P, D = Matrix(A_Test_complex).diagonalize()        
print("Diagonal of a matrix : {}".format(D))  

Matrix : Matrix([[1.00000000000000, 1.0*I], [-1.0*I, 1.00000000000000]]) 
Diagonal of a matrix : Matrix([[0, 0], [0, 2.00000000000000]])
