In [40]:
import numpy as np
import pandas as pd
from sympy import *


np.random.seed(10)
matrix = np.random.randint(2,5,(3,3))
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

#Rank of matrix
print(np.linalg.matrix_rank(matrix))
eigenValue, eigenVector = np.linalg.eig(matrix)
print('Eigen Value : ', eigenValue, sep= " ")
print('Eigen Vector : ', eigenVector, sep= " ")

print('Sum of eigenValue : ', sum(eigenValue), sep=" ")


print('------SVD--------')
print(matrix)
U, D, VT = np.linalg.svd(matrix)
print(U,D,VT, sep="----------------")

print('----------RREF----------')
M = Matrix(matrix)
print(M)
matrix_rref = M.rref()
print(matrix_rref)
print(M.rowspace())
print(M.columnspace())
print(M.nullspace())


from scipy import * 



[[3 3 2]
 [2 3 2]
 [3 3 2]]
(3, 3)
2
int32
2
Eigen Value :  [7.60555128e+00 3.94448725e-01 6.13848056e-16]
Eigen Vector :  [[-6.02549387e-01 -4.79089583e-01  1.11543190e-15]
 [-5.23324442e-01  7.35490546e-01 -5.54700196e-01]
 [-6.02549387e-01 -4.79089583e-01  8.32050294e-01]]
Sum of eigenValue :  7.999999999999997
------SVD--------
[[3 3 2]
 [2 3 2]
 [3 3 2]]
[[-6.01859877e-01  3.71166658e-01 -7.07106781e-01]
 [-5.24908921e-01 -8.51158401e-01  1.15444696e-17]
 [-6.01859877e-01  3.71166658e-01  7.07106781e-01]]----------------[7.78272124e+00 6.55171804e-01 1.36280684e-17]----------------[[-0.59888784 -0.66633326 -0.44422217]
 [ 0.80083291 -0.4983048  -0.3322032 ]
 [ 0.         -0.5547002   0.83205029]]
----------RREF----------
Matrix([[3, 3, 2], [2, 3, 2], [3, 3, 2]])
(Matrix([
[1, 0,   0],
[0, 1, 2/3],
[0, 0,   0]]), (0, 1))
[Matrix([[3, 3, 2]]), Matrix([[0, 3, 2]])]
[Matrix([
[3],
[2],
[3]]), Matrix([
[3],
[3],
[3]])]
[Matrix([
[   0],
[-2/3],
[   1]])]
