In [1]:
import numpy as np

A_Test = np.array([[40,-35,10],[-8,7,-2]])
print(A_Test)

U,D,VT = np.linalg.svd(A_Test)

print(U)
print(np.diag(D))
print(VT)

[[ 40 -35  10]
 [ -8   7  -2]]
[[ 0.98058068  0.19611614]
 [-0.19611614  0.98058068]]
[[5.51543289e+01 0.00000000e+00]
 [0.00000000e+00 7.73106677e-16]]
[[ 0.73960026 -0.64715023  0.18490007]
 [ 0.67212508  0.69580041 -0.25319888]
 [ 0.03520417  0.31154193  0.94958006]]
