In [17]:
import numpy as np
import sympy as s

A = np.array([[5,6,3],[7,2,6],[2,85,9]])
M = s.Matrix(A)
print(A)
print(np.linalg.matrix_rank(A))
print(M.rref())

print('--------------------------')
A = np.array([[2,0,0],[0,4,5],[0,4,3]])
print(A)
lamda,v = np.linalg.eig(A)
print(lamda)
print(v)

[[ 5  6  3]
 [ 7  2  6]
 [ 2 85  9]]
3
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))
--------------------------
[[2 0 0]
 [0 4 5]
 [0 4 3]]
[-1.  8.  2.]
[[ 0.          0.          1.        ]
 [ 0.70710678 -0.78086881  0.        ]
 [-0.70710678 -0.62469505  0.        ]]


In [16]:
A = np.array([[1,2],[3,4]])
print(np.linalg.det(A))

-2.0000000000000004
